language: c
addons:
  apt:
    packages:
      - gdb
      - bc
      - linux-headers-generic

sudo: required

install:
    - ulimit -c
compiler:
  - gcc

before_script:
  - ulimit -c unlimited -S

script:
  - sudo ln -sf $(ls /lib/modules | sed 1q) /lib/modules/$(uname -r)
  - make defconfig ARCH=lib V=1
  # disable DPDK build for a while
  - make clean ARCH=lib V=1 && make library ARCH=lib V=1
  - ./tools/testing/libos/nuse-test.sh
  - make clean ARCH=lib V=1 && make library ARCH=lib OPT=no V=1
  - ./tools/testing/libos/nuse-test.sh
